### ISSUE TITLE
Problem with building on Linux

### ISSUE THREAD

**Issue by DarkMatter-999** [j20001970/GDMP#44]
The latest release does for me as it uses OpenCV v.4.0.7 or requires `libopencv_core.so.407`, while I have openCV v4.9.0 installed.

Build steps I used:
```
git submodule update --init --recursive --depth=1
./setup.py --godot-binary ./Godot_v4.2.2-stable_linux.x86_64
./build.py desktop --type release --output output --arch x86_64
```

Following the build steps as described leads to the following output:
```bash
./build.py desktop --type release --output output --arch x86_64
Starting local Bazel server and connecting to it...
ERROR: Traceback (most recent call last):
        File "/home/matter/.cache/bazel/_bazel_matter/57a186cbfd2843e4219f9d5290032761/external/build_bazel_rules_apple/apple/internal/rule_support.bzl", line 217, column 36, in <toplevel>
                deps_cfg = apple_common.multi_arch_split,
Error: 'apple_common' value has no field or method 'multi_arch_split'
ERROR: error loading package 'mediapipe/gpu': at /home/matter/.cache/bazel/_bazel_matter/57a186cbfd2843e4219f9d5290032761/external/build_bazel_rules_apple/apple/ios.bzl:33:5: at /home/matter/.cache/bazel/_bazel_matter/57a186cbfd2843e4219f9d5290032761/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl:75:5: initialization of module 'apple/internal/rule_support.bzl' failed
ERROR: /home/matter/projects/GDMP/mediapipe/GDMP/gpu/BUILD:1:11: errors encountered resolving select() keys for //GDMP/gpu:gpu_helper
ERROR: Analysis of target '//GDMP/desktop:GDMP' failed; build aborted: Analysis failed
INFO: Elapsed time: 3.086s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
FAILED:
    Fetching repository @@bazel_tools~cc_configure_extension~local_config_cc; starting
    Fetching repository @@npm; starting
    Fetching repository @@com_google_protobuf; starting
    Fetching repository @@yarn; starting
    Fetching repository @@build_bazel_rules_android; starting
    Fetching repository @@rules_java; starting
    Fetching repository @@com_google_absl; starting
    Fetching repository @@com_google_mediapipe_hand_landmarker_task; starting ... (10 fetches)
Traceback (most recent call last):
  File "/home/matter/projects/GDMP/./build.py", line 188, in <module>
    cmd()
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/bazel', 'build', '-c', 'opt', '--copt=-DMESA_EGL_NO_X11_HEADERS', '--copt=-DEGL_NO_X11', '--copt=-fPIC', '//GDMP/desktop:GDMP']' returned non-zero exit status 1.
```

**Comment by DarkMatter-999** [comment]
according to [this issue](https://github.com/google-ai-edge/mediapipe/issues/5105)
changing the `mediapipe/WORKSPACE` to:
```

# ios basic build deps.
http_archive(
    name = "build_bazel_rules_apple",
    sha256 = "9c4f1e1ec4fdfeac5bddb07fa0e872c398e3d8eb0ac596af9c463f9123ace292",
    url = "https://github.com/bazelbuild/rules_apple/releases/download/3.2.1/rules_apple.3.2.1.tar.gz",
    patches = [
        # bypass checking ios unit test runner when building mp ios applications.
        "@//third_party:build_bazel_rules_apple_bypass_test_runner_check.diff"
    ],
    patch_args = [
        "-p1",
    ],
)
```
did help but now the error is:

```bash
./build.py desktop --type release --output output --arch x86_64
INFO: Analyzed target //GDMP/desktop:GDMP (1 packages loaded, 635 targets configured).
ERROR: /home/matter/projects/GDMP/mediapipe/GDMP/tasks/vision/BUILD:3:16: declared output 'GDMP/tasks/vision/face_detection_full_range.tflite' is a dangling symbolic link
ERROR: /home/matter/projects/GDMP/mediapipe/GDMP/tasks/vision/BUILD:3:16: Executing genrule //GDMP/tasks/vision:com_google_mediapipe_face_detection_full_range_tflite_ln failed: not all outputs were created or valid
Target //GDMP/desktop:GDMP failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.378s, Critical Path: 0.07s
INFO: 118 processes: 117 internal, 1 linux-sandbox.
ERROR: Build did NOT complete successfully
Traceback (most recent call last):
  File "/home/matter/projects/GDMP/./build.py", line 188, in <module>
    cmd()
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/bazel', 'build', '-c', 'opt', '--copt=-DMESA_EGL_NO_X11_HEADERS', '--copt=-DEGL_NO_X11', '--copt=-fPIC', '//GDMP/desktop:GDMP']' returned non-zero exit status 1.
```

**Comment by j20001970** [comment]
Hi @DarkMatter-999, I managed to reproduce your first problem by using **Bazel 7.1.1** instead of **6.1.1** specified by `mediapipe` submodule, I think the broken tflite symlink problem are also because of this. Please use Bazel version specified by mediapipe if possible, in order to avoid the behavioural difference across different Bazel versions.

**Comment by DarkMatter-999** [comment]
Yeah you are right.... that was the problem.
I think that the Bazel step should be made clear in the `BUILDING.md`
